language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository

script:
   - ./gradlew clean test -Pkotlin.incremental=false -Pandroid.enableBuildCache=false --continue --stacktrace

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"